spring.application.name=QismaPlus

spring.datasource.url=jdbc:mysql://localhost:8889/Hisbah_Nisbah
spring.datasource.username=root

spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



spring.jpa.show-sql=true

spring.jpa.generate-ddl=true

spring.jpa.hibernate.ddl-auto=create-drop


##دائما اقرا الايرور كامل وافهمها هنا دائما اقدر اشوف المسج ايرور
spring.web.error.include-message=always

spring.web.error.include-stacktrace=always
twilio.account.sid=${ACCOUNT_SID}
twilio.auth.token=${Auth_Token}
twilio.whatsapp.number=+14155238886



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true